name: en_passant
description: A Flutter chess app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+19

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  flame: ^1.2.1
  flame_audio: ^1.3.0
  url_launcher: ^6.1.5
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.5
  google_fonts: ^3.0.1
  stockfish: ^1.0.0
  async: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/icon.png"
  image_path_ios: "assets/icons/icon.png"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  adaptive_icon_background: "assets/icons/icon_background.png"

flutter:
  uses-material-design: true
  assets:
    - assets/font/
    - assets/images/
    - assets/images/pieces/classic/
    - assets/images/pieces/letters/
    - assets/images/pieces/angular/
    - assets/images/pieces/8-bit/
    - assets/images/pieces/videochess/
    - assets/images/pieces/lewischessmen/
    - assets/images/pieces/mexicocity/
    - assets/audio/piece_moved.mp3
